name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run containers
        run: docker compose up --build -d

      - name: Wait for services
        run: sleep 15

      - name: Run tests
        id: tests
        run: docker compose exec app pytest

      - name: Print OK
        if: success()
        run: echo "OK"

      - name: Print FAILED
        if: failure()
        run: echo "FAILED"
        
      - name: Stop containers
        if: always()
        run: docker compose down